### ISSUE TITLE
not working with the new version of hammer js

### ISSUE THREAD

**Issue by jackyon** [apeatling/web-pull-to-refresh#1]
Hi,

I love the demo and it is works great! But when I am trying to integrate the code to my site, I found it is not working with the new version of the hammer js. (v2.0.4)

is it possible to work with the new version? 

Plz advise.

thx.

**Comment by apeatling** [comment]
I am going to try and update these to work with Hammer.js v2, it will need some re-working.

**Comment by jackyon** [comment]
can't wait this ;) thx!

**Comment by quedicesebas** [comment]
Please!!!! thank you, this is the best library right now for pull-to-refresh

**Comment by JimCook57** [comment]
Any status on when you think you will be able to complete this?

**Comment by apeatling** [comment]
I've now updated this to support the latest version of hammer JS, 2.0.4.

**Comment by quedicesebas** [comment]
Thank you
