### ISSUE TITLE
Demo doesn't work on Windows Phone

### ISSUE THREAD

**Issue by HammyHavoc** [apeatling/web-pull-to-refresh#2]
Works a treat in Chrome on my desktop, but in testing on Windows Phone, this doesn't work, any ideas why this might be? Happy to work with you to get this working.

**Comment by apeatling** [comment]
Hey, I actually haven't tested with Windows phone, I don't have a device. I will see about firing up the simulator. Feel free to take a look in the meantime and submit a PR.

**Comment by apeatling** [comment]
Can you try the latest release? This may have been fixed with hammer js v2.
